version: '3.3'

services:
   db:
     image: my-postgres-image 
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
       NAME: ${NAME}
     ports:
             - "5555:5432"
volumes:
    db_data: {}
